
[toolchain]
[features]
resolution = true
skip-lint = false

[programs.mainnet]
pump_meteora = "w7LSvr1Y4DW9xTTdCMdxAGaFTXti2xEu1ykEUeXhTRx"

[programs.devnet]
pump_meteora = "w7LSvr1Y4DW9xTTdCMdxAGaFTXti2xEu1ykEUeXhTRx"

[programs.localnet]
pump_meteora = "w7LSvr1Y4DW9xTTdCMdxAGaFTXti2xEu1ykEUeXhTRx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "./keys/*.json"

[scripts]
build = "rm -rf target && anchor build && mkdir -p target/deploy && cp ./keys/program/3uHJMHzeiqdqQ3LNc5bNVxuCp224HGtStPkv1JUEcabr.json ./target/deploy/pump_meteora-keypair.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
