
[toolchain]
[features]
resolution = true
skip-lint = false

[programs.devnet]
pump_meteora = "G38sN4owkSLDunjcXD66bGLqWEDsCP6cvc5SS6ruSG2j"


[programs.localnet]
pump_meteora = "G38sN4owkSLDunjcXD66bGLqWEDsCP6cvc5SS6ruSG2j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=facb2b5c-c0d2-44b1-8538-986b895bf122"
wallet = "./keys/admin.json"

[scripts]
build = "rm -rf target && anchor build && mkdir -p target/deploy && cp ./keys/program/3uHJMHzeiqdqQ3LNc5bNVxuCp224HGtStPkv1JUEcabr.json ./target/deploy/pump_meteora-keypair.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
